files:
  - source: /translate/en/Overview/*
    translation: /translate/%two_letters_code%/Overview/%original_file_name%
  - source: /translate/en/Other-Plugins/**/*
    translation: /translate/%two_letters_code%/Other-Plugins/**/%original_file_name%
