name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'SlimeTraditionalTranslation/Wiki' &&
      contains(github.event.head_commit.message, '[ci skip]') == false
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/configs/labeler.yml"
