name: Page Sync

on:
  push:
    branches:
    - master
    paths:
    - 'pages/**'

jobs:
  sync:

    name: Synchronize Wiki Pages
    runs-on: ubuntu-latest
    if: github.repository == 'SlimeTraditionalTranslation/Wiki'

    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2

    - name: Syncing Pages
      run: sh src/sync-page.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}