name: Main Wiki Page Sync

on:
  workflow_dispatch: {}
  push:
    branches:
    - master
    paths:
    - 'translate/tw/**'

jobs:
  sync:
    name: Synchronize Wiki Pages
    runs-on: ubuntu-latest
    if: |
      github.repository == 'SlimeTraditionalTranslation/Slimefun-Main-Wiki' &&
      contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2

    - name: Syncing Pages
      run: sh src/sync-page.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
